// GENERATED by scripts/gen-events.ts from docs/tracking-plan.json — do not edit.
export const GLOBAL_PROPERTIES = ["account_id","workspace_id","plan_tier","trial_day","user_role","persona_archetype","is_synthetic","agent_run_id","app_version","route","ui_theme","product","actor_type"] as const;

export const EVENTS = {
  "Marketing Page Viewed": {
    "side": "client",
    "properties": [
      "page",
      "referrer",
      "utm_source",
      "utm_medium",
      "utm_campaign"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "page_view",
    "product": "platform"
  },
  "Pricing Page Viewed": {
    "side": "client",
    "properties": [
      "billing_interval",
      "entry_point"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "view_pricing",
    "product": "platform"
  },
  "Plan Compare Toggled": {
    "side": "client",
    "properties": [
      "billing_interval"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Sign Up Started": {
    "side": "client",
    "properties": [],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Sign Up Completed": {
    "side": "server",
    "properties": [
      "method",
      "signup_source"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "sign_up",
    "product": "platform"
  },
  "Email Verified": {
    "side": "server",
    "properties": [
      "time_to_verify_ms"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Login Completed": {
    "side": "client",
    "properties": [
      "method"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "login",
    "product": "platform"
  },
  "Login Failed": {
    "side": "client",
    "properties": [
      "error_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Password Reset Requested": {
    "side": "client",
    "properties": [],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Onboarding Step Viewed": {
    "side": "client",
    "properties": [
      "step_name",
      "step_index"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Onboarding Step Completed": {
    "side": "client",
    "properties": [
      "step_name",
      "step_index",
      "duration_ms",
      "competitors_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Onboarding Skipped": {
    "side": "client",
    "properties": [
      "step_name"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Onboarding Completed": {
    "side": "client",
    "properties": [
      "duration_ms"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "onboarding_completed",
    "product": "platform"
  },
  "Checklist Item Completed": {
    "side": "client",
    "properties": [
      "item_id",
      "completed_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Query Builder Opened": {
    "side": "client",
    "properties": [
      "builder_mode",
      "is_from_template",
      "entry_point"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Query Previewed": {
    "side": "client",
    "properties": [
      "query_id",
      "builder_mode",
      "preview_result_count",
      "noise_score",
      "operator_count",
      "has_near",
      "exclusion_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Query Validation Failed": {
    "side": "client",
    "properties": [
      "builder_mode",
      "error_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Query Saved": {
    "side": "client",
    "properties": [
      "query_id",
      "builder_mode",
      "operator_count",
      "has_near",
      "exclusion_count",
      "noise_score",
      "languages",
      "sources",
      "is_from_template"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "first_query_saved",
    "product": "listening"
  },
  "Query Edited": {
    "side": "client",
    "properties": [
      "query_id",
      "builder_mode"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Query Paused": {
    "side": "client",
    "properties": [
      "query_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Query Deleted": {
    "side": "client",
    "properties": [
      "query_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Query Backfill Completed": {
    "side": "server",
    "properties": [
      "query_id",
      "backfill_days",
      "matched_count",
      "duration_ms"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "AI Query Generated": {
    "side": "client",
    "properties": [
      "query_id",
      "latency_ms",
      "ai_quota_remaining"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Mentions Feed Viewed": {
    "side": "client",
    "properties": [
      "entry_point",
      "result_count",
      "view_mode"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Mention Filter Applied": {
    "side": "client",
    "properties": [
      "filter_type",
      "filter_value_count",
      "result_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Mention Opened": {
    "side": "client",
    "properties": [
      "source_type",
      "entry_point"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Mention Tagged": {
    "side": "client",
    "properties": [
      "source_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Mention Sentiment Overridden": {
    "side": "client",
    "properties": [
      "from_sentiment",
      "to_sentiment",
      "source_type",
      "lang"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Mention Flagged": {
    "side": "client",
    "properties": [],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Mentions Bulk Action Applied": {
    "side": "client",
    "properties": [
      "action",
      "bulk_size"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Saved View Created": {
    "side": "client",
    "properties": [
      "filter_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Peak Explanation Viewed": {
    "side": "client",
    "properties": [
      "query_id",
      "magnitude_x_baseline",
      "driver_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "AI Summary Generated": {
    "side": "client",
    "properties": [
      "surface",
      "latency_ms",
      "ai_quota_remaining"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Ask AI Question Submitted": {
    "side": "client",
    "properties": [
      "question_length",
      "ai_quota_remaining",
      "latency_ms"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Ask AI Citation Opened": {
    "side": "client",
    "properties": [
      "citation_index"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Insight Shared": {
    "side": "client",
    "properties": [
      "share_channel",
      "insight_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Author Profile Viewed": {
    "side": "client",
    "properties": [
      "author_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Author Watchlisted": {
    "side": "client",
    "properties": [],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Topic Opened": {
    "side": "client",
    "properties": [
      "topic_growth_pct"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Dashboard Created": {
    "side": "client",
    "properties": [
      "template_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Widget Added": {
    "side": "client",
    "properties": [
      "widget_type",
      "is_gated"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Widget Configured": {
    "side": "client",
    "properties": [
      "widget_type",
      "chart_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Widget Moved": {
    "side": "client",
    "properties": [
      "widget_type",
      "move_method"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Dashboard Saved": {
    "side": "client",
    "properties": [
      "widgets_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Dashboard Viewed": {
    "side": "client",
    "properties": [
      "dashboard_type",
      "viewer_is_creator",
      "widgets_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Dashboard Shared": {
    "side": "client",
    "properties": [
      "share_type",
      "recipients_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Widget Drilled Down": {
    "side": "client",
    "properties": [
      "widget_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Alert Created": {
    "side": "client",
    "properties": [
      "alert_type",
      "threshold",
      "channel",
      "backtest_fire_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Alert Triggered": {
    "side": "server",
    "properties": [
      "alert_id",
      "alert_type",
      "severity"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Alert Notification Sent": {
    "side": "server",
    "properties": [
      "alert_id",
      "channel"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Alert Opened": {
    "side": "client",
    "properties": [
      "alert_id",
      "time_to_open_ms"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Alert Acknowledged": {
    "side": "client",
    "properties": [
      "alert_id",
      "time_to_ack_ms"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Alert Muted": {
    "side": "client",
    "properties": [
      "alert_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Alert Deleted": {
    "side": "client",
    "properties": [
      "alert_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Crisis Room Opened": {
    "side": "client",
    "properties": [
      "crisis_id",
      "peak_volume",
      "negative_share"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Crisis Task Created": {
    "side": "client",
    "properties": [
      "crisis_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Stakeholder Update Sent": {
    "side": "client",
    "properties": [
      "crisis_id",
      "recipients_count",
      "is_ai_drafted"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Crisis Room Resolved": {
    "side": "client",
    "properties": [
      "crisis_id",
      "duration_ms"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Report Created": {
    "side": "client",
    "properties": [
      "template_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Report Section Added": {
    "side": "client",
    "properties": [
      "widget_type",
      "source",
      "is_new_report"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Report Exported": {
    "side": "client",
    "properties": [
      "format",
      "template_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Report Scheduled": {
    "side": "client",
    "properties": [
      "schedule_frequency",
      "recipients_count",
      "has_external_recipient"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Report Delivered": {
    "side": "server",
    "properties": [
      "report_id",
      "recipients_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Report Opened": {
    "side": "server",
    "properties": [
      "report_id",
      "channel"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Export Downloaded": {
    "side": "client",
    "properties": [
      "format",
      "row_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "listening"
  },
  "Teammate Invited": {
    "side": "client",
    "properties": [
      "invited_role",
      "invite_source"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Invite Accepted": {
    "side": "server",
    "properties": [
      "days_to_accept"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Comment Added": {
    "side": "client",
    "properties": [
      "target_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "User Mentioned": {
    "side": "client",
    "properties": [],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Workspace Created": {
    "side": "client",
    "properties": [
      "workspaces_count",
      "copied_from_template"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Workspace Switched": {
    "side": "client",
    "properties": [
      "from_workspace_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Workspace Archived": {
    "side": "client",
    "properties": [],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Client Viewer Added": {
    "side": "client",
    "properties": [],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Paywall Viewed": {
    "side": "client",
    "properties": [
      "paywall_trigger",
      "required_plan"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Paywall Dismissed": {
    "side": "client",
    "properties": [
      "paywall_trigger"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Upgrade Started": {
    "side": "client",
    "properties": [
      "paywall_trigger",
      "from_plan",
      "to_plan",
      "billing_interval"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Subscription Started": {
    "side": "server",
    "properties": [
      "plan_tier",
      "billing_interval",
      "motion",
      "mrr"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "subscription_started",
    "product": "platform"
  },
  "Plan Upgraded": {
    "side": "server",
    "properties": [
      "from_plan",
      "to_plan",
      "billing_interval",
      "mrr_delta"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Plan Downgraded": {
    "side": "server",
    "properties": [
      "from_plan",
      "to_plan",
      "mrr_delta"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Seat Added": {
    "side": "server",
    "properties": [
      "seats_total",
      "mrr_delta"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Payment Failed": {
    "side": "server",
    "properties": [
      "attempt_count"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Trial Ended": {
    "side": "server",
    "properties": [
      "converted",
      "queries_count",
      "trial_day_reached"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Quota Threshold Reached": {
    "side": "server",
    "properties": [
      "quota_type",
      "threshold_pct"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Sales Contact Requested": {
    "side": "client",
    "properties": [
      "entry_point",
      "seats_requested"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "generate_lead",
    "product": "platform"
  },
  "Demo Booked": {
    "side": "server",
    "properties": [
      "seats_requested"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "demo_booked",
    "product": "platform"
  },
  "Quote Viewed": {
    "side": "client",
    "properties": [
      "quote_value"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Quote Accepted": {
    "side": "client",
    "properties": [
      "quote_value"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Contract Signed": {
    "side": "server",
    "properties": [
      "quote_value",
      "contract_months"
    ],
    "destinations": [
      "amplitude",
      "warehouse",
      "ga4"
    ],
    "ga4Name": "contract_signed",
    "product": "platform"
  },
  "Cancellation Started": {
    "side": "client",
    "properties": [
      "tenure_days"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Cancellation Reason Submitted": {
    "side": "client",
    "properties": [
      "reason"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Save Offer Viewed": {
    "side": "client",
    "properties": [
      "offer_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Save Offer Accepted": {
    "side": "client",
    "properties": [
      "offer_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Subscription Canceled": {
    "side": "server",
    "properties": [
      "reason",
      "tenure_days"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Account Reactivated": {
    "side": "server",
    "properties": [
      "days_since_cancel"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Command Palette Opened": {
    "side": "client",
    "properties": [],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Keyboard Shortcut Used": {
    "side": "client",
    "properties": [
      "shortcut",
      "context"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Theme Changed": {
    "side": "client",
    "properties": [
      "ui_theme"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Help Opened": {
    "side": "client",
    "properties": [],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Error Displayed": {
    "side": "client",
    "properties": [
      "error_code"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Empty State CTA Clicked": {
    "side": "client",
    "properties": [
      "empty_state_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Notification Opened": {
    "side": "client",
    "properties": [
      "notification_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Email Opened": {
    "side": "server",
    "properties": [
      "email_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Email Link Clicked": {
    "side": "server",
    "properties": [
      "email_type"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Experiment Exposed": {
    "side": "client",
    "properties": [
      "flag_key",
      "variant"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "platform"
  },
  "Product Hub Viewed": {
    "side": "client",
    "properties": [
      "products_available",
      "last_product"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "hub"
  },
  "Product Opened": {
    "side": "client",
    "properties": [
      "product",
      "source"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "hub"
  },
  "Creator Search Run": {
    "side": "client",
    "properties": [
      "result_count",
      "filter_count",
      "sort",
      "has_query",
      "page"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Creator Profile Viewed": {
    "side": "server",
    "properties": [
      "creator_id",
      "platform",
      "niche",
      "audience_locked",
      "profile_views_used"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Creator List Created": {
    "side": "server",
    "properties": [
      "list_id",
      "source"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Creator Added To List": {
    "side": "server",
    "properties": [
      "list_id",
      "creator_id",
      "source"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Creator Removed From List": {
    "side": "server",
    "properties": [
      "list_id",
      "creator_id",
      "source"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Creator List Exported": {
    "side": "server",
    "properties": [
      "list_id",
      "creator_count",
      "format"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Campaign Created": {
    "side": "server",
    "properties": [
      "campaign_id",
      "objective",
      "budget_usd"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Campaign Status Changed": {
    "side": "server",
    "properties": [
      "campaign_id",
      "from_status",
      "to_status"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Campaign Creators Added": {
    "side": "server",
    "properties": [
      "campaign_id",
      "creator_count",
      "source"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Campaign Creator Status Changed": {
    "side": "server",
    "properties": [
      "campaign_id",
      "creator_id",
      "from_status",
      "to_status"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Campaign Creator Removed": {
    "side": "server",
    "properties": [
      "campaign_id",
      "creator_id"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Creator Invitation Sent": {
    "side": "server",
    "properties": [
      "campaign_id",
      "creator_id",
      "offered_usd",
      "round"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Creator Portal Viewed": {
    "side": "server",
    "properties": [
      "campaign_id",
      "creator_id",
      "invite_state"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "creator_portal"
  },
  "Creator Invitation Answered": {
    "side": "server",
    "properties": [
      "campaign_id",
      "creator_id",
      "response",
      "counter_usd"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "creator_portal"
  },
  "Creator Counter Resolved": {
    "side": "server",
    "properties": [
      "campaign_id",
      "creator_id",
      "decision"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  },
  "Creator Content Submitted": {
    "side": "server",
    "properties": [
      "campaign_id",
      "creator_id",
      "version"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "creator_portal"
  },
  "Creator Content Reviewed": {
    "side": "server",
    "properties": [
      "campaign_id",
      "creator_id",
      "decision",
      "version"
    ],
    "destinations": [
      "amplitude",
      "warehouse"
    ],
    "ga4Name": null,
    "product": "influencers"
  }
} as const;

export type EventName = keyof typeof EVENTS;
export type Prop = string | number | boolean | null | undefined | string[];
/** Event-specific properties only; global properties are attached by the tracker. */
export type EventProps<N extends EventName> = Partial<Record<(typeof EVENTS)[N]["properties"][number], Prop>>;
