// Generates lib/analytics/events.ts from docs/tracking-plan.json (the source of truth).
import { readFileSync, writeFileSync } from "node:fs";

interface PlanEvent {
  name: string;
  side: "client" | "server";
  properties: string[];
  destinations: string[];
  ga4_name?: string;
}
const plan = JSON.parse(readFileSync("docs/tracking-plan.json", "utf8")) as {
  global_properties: string[];
  events: PlanEvent[];
};

const events = Object.fromEntries(
  plan.events.map((e) => [
    e.name,
    {
      side: e.side,
      properties: e.properties,
      destinations: e.destinations,
      ga4Name: e.ga4_name ?? null,
    },
  ]),
);

writeFileSync(
  "lib/analytics/events.ts",
  `// GENERATED by scripts/gen-events.ts from docs/tracking-plan.json — do not edit.
export const GLOBAL_PROPERTIES = ${JSON.stringify(plan.global_properties)} as const;

export const EVENTS = ${JSON.stringify(events, null, 2)} as const;

export type EventName = keyof typeof EVENTS;
export type Prop = string | number | boolean | null | undefined | string[];
/** Event-specific properties only; global properties are attached by the tracker. */
export type EventProps<N extends EventName> = Partial<Record<(typeof EVENTS)[N]["properties"][number], Prop>>;
`,
);
console.log(`wrote ${plan.events.length} events`);
