// Compiles lib/query/grammar.peggy -> lib/query/parser.generated.mjs (isomorphic: server + browser).
import { readFileSync, writeFileSync } from "node:fs";
import peggy from "peggy";

const source = peggy.generate(readFileSync("lib/query/grammar.peggy", "utf8"), {
  output: "source",
  format: "es",
}) as unknown as string;
writeFileSync(
  "lib/query/parser.generated.mjs",
  `// GENERATED by scripts/gen-grammar.ts from grammar.peggy — do not edit.\n/* eslint-disable */\n${source}`,
);
console.log("wrote lib/query/parser.generated.mjs");
